#!/bin/bash
set -e
if [[ $# -ne 1 ]]; then
    echo "usage: $(basename $0) docker-image-name (e.g. spf6_thru_11)"
    exit 1
fi
IMAGE=$1
if [[ ! -f DockerEnv-$IMAGE ]]; then
    echo DockerEnv DockerEnv-$IMAGE not found
    exit 1
fi
MYUID=$(id -u)
MYGID=$(id -g)
MYLOG=$LOGNAME
tmp=$(mktemp)
sed -e "s/LOGNAME/$MYLOG/g" -e "s/UID/$MYUID/g" -e "s/GID/$MYGID/g" DockerEnv-$IMAGE > $tmp
docker build -t $IMAGE -f $tmp .
rm -f $tmp
