#!/bin/bash

if [ $# -ne 1 ]; then
 echo "usage: $(basename $0) host"
 exit 1
fi
case $(basename $0) in
PowerStatus)	verb=status	;;
PowerOn)	verb=on		;;
PowerOff)	verb=off	;;
PowerReset)	verb=reset	;;
esac
case ${1} in
 colfax)
	u=root
	p=passwd
	h=${1}-ipmi
	;;
 r2d2)
	u=admin
	p=admin
	h=${1}-ipmi
	;;
 *)
	echo nope
	exit 1
esac
ipmitool -H $h -U $u -P $p power $verb
exit 0
