#!/bin/sh
#
# Copyright (c) 2012,2021 by Matthew Jacob
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice immediately at the beginning of the file, without modification,
#    this list of conditions, and the following disclaimer.
# 2. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
case `uname -o` in
FreeBSD)
 if [ $# -gt 1 ]; then
  date -j -f "%a %b %d %T %Z %Y" "$*" "+%s"
 elif [ $# -eq 1 ]; then
  date -j -f "%s" $1 +"%a %b %d %T %Z %Y"
 elif [ $# -eq 0 ]; then
  date  +%s
 fi
 ;;
*inux)
 if [ $# -gt 1 ]; then
  date --date="$*" "+%s"
 elif [ $# -eq 1 ]; then
  date --date="@${1}" +"%a %b %d %T %Z %Y"
 elif [ $# -eq 0 ]; then
  date +%s
 fi
 ;;
esac
exit 0
