#!/bin/bash
set -o pipefail
for host in $*; do
 echo View the full certificate chain and verify against system trust store from $host
 echo | openssl s_client -connect $1:443 -servername $1 -showcerts 2>/dev/null | openssl x509 -noout -subject -issuer -dates || continue
 echo ++++++
 echo Check verification status '(look for "Verify return code: 0 (ok)")' for $host
 echo | openssl s_client -connect $1:443 -servername $1 -CApath /etc/ssl/certs/ 2>&1 | grep "Verify return code"   
done
