#!/bin/sh
#
# Copyright (c) 1999, 2013 Matthew Jacob
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#
# The full GNU General Public License is included in this distribution in
# the file called "COPYING".
#
#      $Id: creatfil,v 1.4 2013/04/14 20:48:31 mjacob Exp $
#
FILESIZ=${FILESIZ-1m}
FILECNT=${FILECNT-10}
PATFLAG=${PATFLAG--p}

if [ $# -ne 1 ]; then
	echo "usage: $0 testdirectory"
	exit 1
fi

echo "Begin Create Pass"
i=1
while [ $i -le ${FILECNT} ]
do
	filbuf ${PATFLAG} $i -s ${FILESIZ} -o $1/file.$i &
	i=`expr $i '+' 1`
done
wait
